### ISSUE TITLE
CAN 문서 Review

### ISSUE THREAD

**Issue by hspy** [MCUsGarage/MCUsGarage.github.io#33]
내용이 방대함, 좀더 세분화가 되면 좋을것 같음.
특히 내용의 절반 이상이 통신 프로토콜에 대한 기본기가 없는 경우 이해하기 힘든 경우가 많음.
1. 노드에 대한 사전 설명이 별도로 있으면 좋을 것 같음.
2. 여러 노드가 동시에 데이터를 전송해서 데이터를 사용하지 못하는 경우(충돌,collision)도 -> 충돌(collision)
3. 차동 신호 방식 사진이 있으면 좋을것같음.
4. CSMA/CD(Carrier Sense Multiple Access / Collision Detection)와 AMP(Arbitration on Message Priority)
한줄 글 뿐만 아니라 CSMA, AMP 구조에 대한 간단한 설명 혹은 그림이 추가 되면 좋을듯.
5. OSI 7 Layer 좀더 자세히 설명하면 해당 네트워크 구조를 이해하는데 더 좋을 것 같음.
6. 비트스트림이 무엇인지? 자세히 설명해야 입문자들이 이해하기 편할 것 같음
7. 직렬 통신 병렬 통신 그림 비교가 있으면 좋을 것 같음(직관적 비교)
8. 버스 네트워크 설명 중 half duplex 에 대한 설명, master-slave 구조 설명 MAC 구조 설명 필요할 것으로 보임.
9. 메세지 송 수신 과정에 대한 state 천이도? 같은것이 있으면 더 이해도가 높아질 것 같음.
10. 이번 릴리즈 목표 범위는 어디까지인지? 1-3 Error 이후 Concerning CAN-based Protocols에서부터는 내용이 확 줄어든듯, 
CAN Based Protocol 은 자동차부터 시작하여 산업 전반에 다 쓰여서 너무 많은 프로토콜이 존재하는데 어디까지 커버할것인지 정하는 것도 중요해보임 (KWP2000같은거도 커버할것인지?)
11. 2. The First Journey의 경우 예제 코드에 대한 코드 블럭도 포함되면 보기 편할 것 같음.
12. 코드 관련 설명 중 state diagram이나 상태 천이도 등을 포함하여 설명하면 직관적으로 보기 편할 것 같음.

**Comment by dongjuk157** [comment]
리뷰 감사합니다
그림이랑 자세한 설명을 추가 해야겠네요

릴리즈는 CAN FD 까지 정리하는게 목표입니다. 1.3 CAN-based protocols 는 chatper 5 들어가는 내용이랑 중복될거같아 삭제될 예정입니다. 많은 프로토콜이 존재하긴하지만 우선 제가 사용할만한 것들이나 적당히 들어본 것들 위주로 작성할 예정입니다. 상위 호환되거나 발전된 프로토콜이 있으면 추가하지 않고 적당히 설명만 하고 넘어가려고 합니다(KWP2000 -> UDS) 

상태 천이도는 추후에 추가하겠습니다.

ch2 예제에 대한 코드는 이미 추가되어있는데 더 필요한걸까요?

**Comment by dongjuk157** [comment]
통신 프로토콜관련 위키피디아 링크 추가
- CSMA/CD(Carrier Sense Multiple Access / Collision Detection), AMP(Arbitration on Message Priority) 등
이미지 추가
- CSMA/CD flow chart 추가

내용 관련 
- 1.2. CAN FD 이후 챕터는 1.1. CAN 정리 부터 끝내놓고 다시 작성 예정. 그 전까진 주석 처리로 실제 페이지에서 안보이게 처리 
- 1.3. Concerning CAN-based Protocols -> 챕터 5로 이동. 어차피 겹치는 내용이었고 내용자체도 많이 부실했기 때문에 이후 챕터에서 자세히 작성 예정.
- 2. The First Journey: 이 챕터는 예제니까 일단 주석 처리 하지 않음.

**Comment by dongjuk157** [comment]
이후 추가할 내용

1. 통신과 관련해서 기본 지식이 필요한 내용들
   - 자세한 설명 혹은 위키 링크, 이미지 추가 등 필요 
   - 노드, 비트스트림, 차동 신호 방식, OSI 7 Layer, 직렬 통신 병렬 통신(비교)

**Comment by dongjuk157** [comment]
통신 관련 위키피디아 링크 추가
- 노드, 비트스트림, 차동 신호 방식, OSI 7 Layer
내용 추가
- 직렬 통신 병렬 통신(비교)
